name: Test
on: push

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10.6"
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
      - name: Cache
        id: cache-pipenv
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: pipenv-${{ hashFiles('**/Pipfile.lock') }}
      - name: Install dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: pipenv sync --dev
      - name: Download xlsx
        run: |
          mkdir resources
          wget https://www.soumu.go.jp/main_content/000730858.xlsx -O resources/000730858.xlsx
      - name: Lint with Flake8
        run: pipenv run flake8
      - name: isort
        run: pipenv run isort . -c
      - name: Test with pytest
        run: pipenv run pytest
